language: android

script: "./gradlew build"
android:
  components:
    - platform-tools
    - tools
    - build-tools-26.0.2
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-15
    - sys-img-armeabi-v7a-android-21

deploy:
  provider: releases
api_key:
  secure: yourgithubkey
file: app/build/outputs/apk/app-debug.apk
skip_cleanup: true
on:
  repo: username/reponame
  tags: true
  all_branches: true

notifications:
  email:
    - you@you.com
    on_success: always
    on_failure: always